spring.application.name=WebFinanceApp

# Server
server.port=8080

# H2 in-memory (ime baze vezano za tvoj artifact)
spring.datasource.url=jdbc:h2:mem:webfinanceapp;MODE=PostgreSQL;DATABASE_TO_UPPER=false;DB_CLOSE_DELAY=-1
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# JPA/Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# H2 konzola
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# SQL init (da se data.sql uvek izvrsi POSLE kreiranja seme)
spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=always
spring.sql.init.encoding=UTF-8

# JWT konfiguracija (primer vrednosti)
app.jwt.secret=change-me-32-bytes-minimum-change-me-32-b
app.jwt.expires=3600

# u sekundama (3600s=1h)

# H2 console i security sitnice
spring.security.filter.dispatcher-types=REQUEST,ERROR